var oSec_article_con = document.querySelector('.sec_article_con');
    var product = [
        {
            img : 'images/p1.jpg',
            h4 : '深圳卫视2019年度品牌形象',
            h5 : '影视-栏目包装',
            a1 : 8982,
            a2 : 29,
            a3 : 486,
            img2 : 'images/img1.jpg',
            p :  '俊灵儿',
            a4 : '1天前',
        },
        {
            img : 'images/p2.jpg',
            h4 : '对战',
            h5 : '插画-商业插画',
            a1 : '6015',
            a2 : 27,
            a3 : 176,
            img2 : 'images/img2.jpg',
            p :  '焜琼',
            a4 : '1天前',
        },
        {
            img : 'images/p3.jpg',
            h4 : '部族领袖',
            h5 : '三维-人物/生物',
            a1 : 8982,
            a2 : 29,
            a3 : 486,
            img2 : 'images/img3.jpg',
            p :  '俊灵儿',
            a4 : '1天前',
        },
        {
            img : 'images/p4.jpg',
            h4 : '女孩的花',
            h5 : '插画-商业插画',
            a1 : 7686,
            a2 : 23,
            a3 : 373,
            img2 : 'images/img4.jpg',
            p :  '小石头1125',
            a4 : '2天前',
        },
        {
            img : 'images/p5.jpg',
            h4 : '雪山星空',
            h5 : '摄影-风光',
            a1 : 8982,
            a2 : 29,
            a3 : 486,
            img2 : 'images/img5.jpg',
            p :  '看看',
            a4 : '1天前',
        },
        {
            img : 'images/p6.jpg',
            h4 : '母亲节，设计速成指南',
            h5 : '特别企划',
            a1 : '',
            a2 : '',
            a3 : '',
            img2 : 'images/img6.jpg',
            p :  '站酷海洛',
            a4 : '推广',
        },
        {
            img : 'images/p7.jpg',
            h4 : '插画一百/重启未知',
            h5 : '插画-商业插画',
            a1 : 8982,
            a2 : 29,
            a3 : 486,
            img2 : 'images/img7.jpg',
            p :  '车车',
            a4 : '1天前',
        },
        {
            img : 'images/p8.jpg',
            h4 : '好课免费领',
            h5 : '特别企划',
            a1 : '',
            a2 : '',
            a3 : '',
            img2 : 'images/img8.jpg',
            p :  '站酷高手',
            a4 : '推广',
        },
        {
            img : 'images/p9.jpg',
            h4 : '梅兰竹菊',
            h5 : '插画-其他插画',
            a1 : 3744,
            a2 : 9,
            a3 : 83,
            img2 : 'images/img9.jpg',
            p :  '佳仙人',
            a4 : '23小时前',
        },
        {
            img : 'images/p10.jpg',
            h4 : '《窗子里的人》绘本',
            h5 : '插画-绘本',
            a1 : '1.0万',
            a2 : 38,
            a3 : 387,
            img2 : 'images/img10.jpg',
            p :  '赵阿弧',
            a4 : '1天前',
        },
        {
            img : 'images/p11.jpg',
            h4 : '深圳卫视2019年度品牌形象',
            h5 : '影视-栏目包装',
            a1 : 8982,
            a2 : 29,
            a3 : 486,
            img2 : 'images/img11.jpg',
            p :  '俊灵儿',
            a4 : '1天前',
        },
        {
            img : 'images/p12.jpg',
            h4 : '对战',
            h5 : '插画-商业插画',
            a1 : '6015',
            a2 : 27,
            a3 : 176,
            img2 : 'images/img12.jpg',
            p :  '焜琼',
            a4 : '1天前',
        },
        {
            img : 'images/p13.jpg',
            h4 : '部族领袖',
            h5 : '三维-人物/生物',
            a1 : 8982,
            a2 : 29,
            a3 : 486,
            img2 : 'images/img13.jpg',
            p :  '俊灵儿',
            a4 : '1天前',
        },
        {
            img : 'images/p14.jpg',
            h4 : '女孩的花',
            h5 : '插画-商业插画',
            a1 : 7686,
            a2 : 23,
            a3 : 373,
            img2 : 'images/img14.jpg',
            p :  '小石头1125',
            a4 : '2天前',
        },
        {
            img : 'images/p15.jpg',
            h4 : '雪山星空',
            h5 : '摄影-风光',
            a1 : 8982,
            a2 : 29,
            a3 : 486,
            img2 : 'images/img15.jpg',
            p :  '看看',
            a4 : '1天前',
        },
        {
            img : 'images/p16.jpg',
            h4 : '母亲节，设计速成指南',
            h5 : '特别企划',
            a1 : '',
            a2 : '',
            a3 : '',
            img2 : 'images/img16.jpg',
            p :  '站酷海洛',
            a4 : '推广',
        },
        {
            img : 'images/p17.jpg',
            h4 : '插画一百/重启未知',
            h5 : '插画-商业插画',
            a1 : 8982,
            a2 : 29,
            a3 : 486,
            img2 : 'images/img17.jpg',
            p :  '车车',
            a4 : '1天前',
        },
        {
            img : 'images/p18.jpg',
            h4 : '好课免费领',
            h5 : '特别企划',
            a1 : '',
            a2 : '',
            a3 : '',
            img2 : 'images/img18.jpg',
            p :  '站酷高手',
            a4 : '推广',
        },
        {
            img : 'images/p19.jpg',
            h4 : '梅兰竹菊',
            h5 : '插画-其他插画',
            a1 : 3744,
            a2 : 9,
            a3 : 83,
            img2 : 'images/img19.jpg',
            p :  '佳仙人',
            a4 : '23小时前',
        },
        {
            img : 'images/p20.jpg',
            h4 : '《窗子里的人》绘本',
            h5 : '插画-绘本',
            a1 : '1.0万',
            a2 : 38,
            a3 : 387,
            img2 : 'images/img20.jpg',
            p :  '赵阿弧',
            a4 : '1天前',
        }
    ]

    var str = '';
    for(var i = 0 ; i < product.length ; i++){
        str += `
        <div class="module">
            <img src="${product[i].img}" alt="">
            <h4><a href="">${product[i].h4}</a><i class="iconfont icon-sousuo1"></i></h4>
            <h5>${product[i].h5}</h5>
            <ul>
                <li><i class="iconfont icon-sousuo1"></i><a>${product[i].a1}</a></li>
                <li><i class="iconfont icon-sousuo1"></i><a>${product[i].a2}</a></li>
                <li><i class="iconfont icon-sousuo1"></i><a>${product[i].a3}</a></li>
            </ul>
            <div>
                <p><img src="${product[i].img2}"><a href="">${product[i].p}</a></p>
                <a href="" class="btm">${product[i].a4}</a>
            </div>
        </div>
        `
    }

    oSec_article_con.innerHTML = str;